# Generated by Django 4.0.1 on 2022-02-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=30, null=True)),
                ('stock_exchange', models.CharField(default='NSE', max_length=10)),
                ('demo_price', models.IntegerField(null=True)),
            ],
        ),
    ]
