# Generated by Django 4.0.1 on 2022-02-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='demo_price',
            new_name='price',
        ),
    ]
