# Generated by Django 4.0.1 on 2022-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_demo_price_stocks_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
