# Generated by Django 4.0.1 on 2022-02-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_stocks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
